const std = @import("std");
pub const request = @import("request.zig");
pub const response = @import("response.zig");
pub const router = @import("router.zig");
pub const app = @import("app.zig");
pub const context = @import("context.zig");
pub const http_exception = @import("http_exception.zig");
pub const middleware_helpers = @import("middleware_helpers.zig");
pub const realtime = @import("realtime.zig");
pub const route_helper = @import("route_helper.zig");
pub const server = @import("server.zig");
pub const serve_static_helper = @import("serve_static.zig");
pub const validator_helper = @import("validator.zig");
pub const path = @import("path.zig");

pub const Request = request.Request;
pub const Param = request.Param;
pub const Header = request.Header;
pub const MatchedRoute = request.MatchedRoute;
pub const MatchedRouteKind = request.MatchedRouteKind;
pub const ValidationTarget = request.ValidationTarget;
pub const RequestBlob = request.RequestBlob;
pub const ParseBodyError = request.ParseBodyError;
pub const ParseBodyOptions = request.ParseBodyOptions;
pub const ParsedBody = request.ParsedBody;
pub const ParsedBodyEntry = request.ParsedBodyEntry;
pub const ParsedBodyField = request.ParsedBodyField;
pub const ParsedHeaders = request.ParsedHeaders;
pub const ParsedHeaderEntry = request.ParsedHeaderEntry;
pub const ParsedHeaderField = request.ParsedHeaderField;
pub const ParsedMultipart = request.ParsedMultipart;
pub const ParsedMultipartFile = request.ParsedMultipartFile;
pub const ParsedMultipartFiles = request.ParsedMultipartFiles;
pub const ParsedMultipartFileEntry = request.ParsedMultipartFileEntry;
pub const ParsedMultipartFileField = request.ParsedMultipartFileField;
pub const ParsedFormData = request.ParsedFormData;
pub const ParsedFormFile = request.ParsedFormFile;
pub const ParsedFormFiles = request.ParsedFormFiles;
pub const ParsedFormFileEntry = request.ParsedFormFileEntry;
pub const ParsedFormFileField = request.ParsedFormFileField;
pub const Response = response.Response;
pub const App = app.App;
pub const Context = context.Context;
pub const Router = router.Router;
pub const Route = router.Route;
pub const Server = server.Server;
pub const Options = server.Options;
pub const AppOptions = app.App.Options;
pub const AppRequestOptions = app.App.RequestOptions;
pub const RawRequest = app.App.RawRequest;
pub const FetchRawOptions = app.App.FetchRawOptions;
pub const CookieOptions = response.CookieOptions;
pub const DeleteCookieOptions = response.DeleteCookieOptions;
pub const CookieError = response.CookieError;
pub const SameSite = response.SameSite;
pub const CookiePriority = response.CookiePriority;
pub const CookiePrefix = response.CookiePrefix;
pub const HTTPException = http_exception.HTTPException;
pub const CORSOrigin = middleware_helpers.CORSOrigin;
pub const CORSOptions = middleware_helpers.CORSOptions;
pub const LoggerOptions = middleware_helpers.LoggerOptions;
pub const LoggerEvent = middleware_helpers.LoggerEvent;
pub const ServeStaticOptions = serve_static_helper.ServeStaticOptions;
pub const SSEEvent = realtime.SSEEvent;
pub const WebSocketAcceptOptions = realtime.WebSocketAcceptOptions;
pub const WebSocketUpgradeError = realtime.WebSocketUpgradeError;

pub const html = response.html;
pub const body = response.body;
pub const json = response.json;
pub const text = response.text;
pub const notFound = response.notFound;
pub const redirect = response.redirect;
pub const options = response.options;
pub const methodNotAllowed = response.methodNotAllowed;
pub const internalError = response.internalError;
pub const typedJson = response.typedJson;
pub const parseJson = response.parseJson;
pub const generateCookie = response.generateCookie;
pub const generateDeleteCookie = response.generateDeleteCookie;
pub const cleanPath = path.cleanPath;
pub const routeOnError = app.routeOnError;
pub const validator = validator_helper.validator;
pub const validatorForm = validator_helper.form;
pub const validatorJson = validator_helper.json;
pub const validatorQuery = validator_helper.query;
pub const validatorHeader = validator_helper.header;
pub const validatorCookie = validator_helper.cookie;
pub const validatorParam = validator_helper.param;
pub const cors = middleware_helpers.cors;
pub const logger = middleware_helpers.logger;
pub const serveStatic = serve_static_helper.serveStatic;
pub const sse = realtime.sse;
pub const isWebSocketUpgrade = realtime.isWebSocketUpgrade;
pub const acceptWebSocket = realtime.acceptWebSocket;
pub const routePath = route_helper.routePath;
pub const baseRoutePath = route_helper.baseRoutePath;
pub const matchedRoutes = route_helper.matchedRoutes;

test {
    _ = request;
    _ = response;
    _ = router;
    _ = app;
    _ = context;
    _ = http_exception;
    _ = middleware_helpers;
    _ = realtime;
    _ = route_helper;
    _ = server;
    _ = serve_static_helper;
    _ = validator_helper;
    _ = path;

    try std.testing.expect(!@hasDecl(@This(), "http"));
    try std.testing.expect(!@hasDecl(@This(), "extract"));
    try std.testing.expect(!@hasDecl(@This(), "static"));
    try std.testing.expect(!@hasDecl(@This(), "web"));
    try std.testing.expect(!@hasDecl(@This(), "http1"));
    try std.testing.expect(!@hasDecl(@This(), "thin"));

    try std.testing.expect(@hasDecl(@This(), "App"));
    try std.testing.expect(@hasDecl(@This(), "Context"));
    try std.testing.expect(@hasDecl(@This(), "Request"));
    try std.testing.expect(@hasDecl(@This(), "Response"));
    try std.testing.expect(@hasDecl(@This(), "Router"));
    try std.testing.expect(@hasDecl(@This(), "Server"));
    try std.testing.expect(@hasDecl(@This(), "typedJson"));
    try std.testing.expect(@hasDecl(@This(), "cleanPath"));
}
